Feature:
  In order to display video content
  As a public user
  I need to view the content of a video

  Scenario: search for a video (DAM-83)
    Given I am on the home page
    And I fill in "q" with "rockhall:fixture_pbcore_document1"
    When I press "submit"
    Then I should see a link to "the show document page for rockhall:fixture_pbcore_document1"
    And I should see "Rock and Roll Hall of Fame induction ceremony. Part 1."

  Scenario: search for a video barcode (DAM-83)
    Given I am on the home page
    And I fill in "q" with "39156042551098"
    When I press "submit"
    Then I should see a link to "the show document page for rockhall:fixture_pbcore_document1"
    And I should see "Rock and Roll Hall of Fame induction ceremony. Part 1."

  @wip
  Scenario: Viewable metadata (DAM-131)
    Given I am on the show document page for rockhall:fixture_pbcore_document1
    Then I should see the heading "Video"
    And I should see the heading "Content"
    And I should see the field title "main_title" contain "Main Title"
    And I should see the field content "main_title" contain "Rock and Roll Hall of Fame induction ceremony. Part 1."
    And I should see the field title "alternative_title" contain "Alternative Title"
    And I should see the field content "alternative_title" contain "[Tape label title] Induction ceremony, line cut reel #20A, 03/15/99."
    And I should see the field title "summary" contain "Summary"
    And I should see the field content "summary" contain "(1 of 3) Uncut performances and award presentations from the 1999 ceremony."
    And I should see the field title "subject" contain "Subject"
    And I should see the field content "subject" contain "Rock and Roll Hall of Fame and Museum."
    And I should see the field content "subject" contain "Rock music--History and criticism."
    And I should see the field content "subject" contain "Inductee"
    And I should see the field content "subject" contain "Rock musicians."
    And I should see the field title "genre" contain "Genre"
    And I should see the field content "genre" contain "Award presentations (Motion pictures)"
    And I should see the field content "genre" contain "Rock concert films."
    And I should see the field title "event_series" contain "Event Series"
    And I should see the field content "event_series" contain "Rock and Roll Hall of Fame and Museum. Annual induction ceremony. 1999."
    And I should see the field title "event_place" contain "Event Place"
    And I should see the field content "event_place" contain "New York, NY"
    And I should see the field title "event_date" contain "Event Date"
    And I should see the field content "event_date" contain "1999-03-15"
    And I should see the field title "note" contain "Note"
    And I should see the field content "note" contain "http://rockhall.com/inductees/ceremonies/1999/"
    And I should see the field title "contributor" contain "Contributor"
    And I should see the field content "main_title" contain "Springsteen, Bruce"
    And I should see the field content "main_title" contain "McCartney, Paul."
    And I should see the field content "main_title" contain "Joel, Billy."
    And I should see the field content "main_title" contain "Brown, Charles, 1922-1999."
    And I should see the field content "main_title" contain "Mayfield, Curtis."
    And I should see the field content "main_title" contain "Shannon, Del."
    And I should see the field content "main_title" contain "Springfield, Dusty."
    And I should see the field content "main_title" contain "Staple Singers."
    And I should see the field content "main_title" contain "Pickett, Wilson"
    And I should see the field title "publisher" contain "Publisher"
    And I should see the field content "main_title" contain "Rock and Roll Hall of Fame Foundation"
    And I should see the heading "Original"
    And I should see "Creation Date"
    And I should see "1999-03-15"
    And I should see "Barcode"
    And I should see "39156042551098"
    And I should see "Repository"
    And I should see "2809 Woodland Ave."
    And I should see "Format"
    And I should see "Betacam"
    And I should see "Standard"
    And I should see "NTSC"
    And I should see "Media Type"
    And I should see "Moving image"
    And I should see "Generation"
    And I should see "Original"
    And I should see "Language"
    And I should see "English"
    And I should see "Colors"
    And I should see "Color"
    And I should see "Archival Collection"
    And I should see "Rock and Roll Hall of Fame and Museum Records. Education and Public Programs Division."
    And I should see "Archival Series"
    And I should see "Audiovisual Materials"
    And I should see "Collection Number"
    And I should see "ARC.0002"
    And I should see "Accession Number"
    And I should see "LA.2003.01.001"
    And I should see "Rockhall"
    And I should see "Depositor"
    And I should see "archivist1@example.com"
    And I should see "Review Information"
    And I should see "Public"
    And I should see "original"
    And I should see "h264"

  Scenario: Videos not ingested yet (DAM-131)
    Given I am logged in as "archivist1@example.com"
    When I am on the show document page for rockhall:fixture_pbcore_document2
    Then I should see "Content" within ".section-title"
    And I should see "Pre-Ingest Video"
    And I should see "This is a sample record of a video that has not been ingested or reviewed yet."

