Feature:
  In order to catalog video content
  As a library staff user
  I need to edit the metadata of a video

  Scenario: edit video object (DAM-131)
    Given I am logged in as "archivist1@example.com"
    Given I am on the first workflow edit page for rockhall:fixture_pbcore_document1
    Then I should see "Required Title"
    And the "main_title" field should contain "Rock and Roll Hall of Fame induction ceremony. Part 1."
    And the "alternative_title_0" field should contain "\[Tape label title\] Induction ceremony, line cut reel \#20A, 03\/15\/99."
    And the "summary_0" field should contain "\(1 of 3\) Uncut performances and award presentations from the 1999 ceremony."
    And the "note_0" field should contain "http\:\/\/rockhall\.com\/inductees\/ceremonies\/1999\/"
    When I press "Submit"
    Then I should see "Required Title"
    When I choose "wf_step_titles"
    And I press "Submit"
    Then I should see "Subject Fields"
    And the "lc_subject_0" field should contain "Rock music--History and criticism."
    And the "lc_subject_1" field should contain "Rock and Roll Hall of Fame and Museum."
    And the "lc_subject_2" field should contain "Inductee"
    And the "lc_subject_3" field should contain "Rock musicians."
    And I should see "Genre Fields"
    And the "lc_genre_0" field should contain "Award presentations \(Motion pictures\)"
    And the "lc_genre_1" field should contain "Rock concert films."
    And I should see "Event Fields"
    And the "event_series" field should contain "Rock and Roll Hall of Fame and Museum\. Annual induction ceremony\. 1999\."
    And the "event_place" field should contain "New York, NY"
    And the "event_date" field should contain "1999-03-15"
    When I press "Submit"
    Then I should see "Subject Fields"
    When I choose "wf_step_subjects"
    And I press "Submit"
    Then I should see "Contributors"
    And the "contributor_0_name" field should contain "Springsteen, Bruce"
    And the "contributor_0_role" field should contain "recipient"
    And I should see "Publishers"
    And the "publisher_0_name" field should contain "Rock and Roll Hall of Fame Foundation"
    And the "publisher_0_role" field should contain "presenter"
    When I choose "wf_step_persons"
    And I press "Submit"
    Then I should see "Original Item"
    And the "creation_date" field should contain "1999-03-15"
    And the "barcode" field should contain "39156042551098"
    And I should see "Archival Information"
    And the "archival_collection" field should contain "Rock and Roll Hall of Fame and Museum Records. Education and Public Programs Division."
    When I press "Submit"
    Then I should see "Rockhall Fields"
    When I press "Submit"
    Then I should see "Rockhall Fields"
    When I choose "wf_step_rockhall"
    And I press "Submit"
    Then I should see "Group Permissions"

  Scenario: Navigating different parts of the workflow (DAM-169)
    Given I am logged in as "archivist1@example.com"
    Given I am on the first workflow edit page for rockhall:fixture_pbcore_document1
    When I choose "wf_step_titles"
    And I press "Go to"
    Then I should see "Required Title"
    When I choose "wf_step_subjects"
    And I press "Go to"
    Then I should see "Subject Fields"
    When I choose "wf_step_persons"
    And I press "Go to"
    Then I should see "Contributors"
    When I choose "wf_step_original"
    And I press "Go to"
    Then I should see "Original Item"
    When I choose "wf_step_rockhall"
    And I press "Go to"
    Then I should see "Rockhall Fields"
    When I choose "wf_step_permissions"
    And I press "Go to"
    Then I should see "Group Permissions"


