Feature:
  In order to prepare existing analog or digital video content for ingestion
  As a archivist or reviewer
  I need to created a new record for the video

  Scenario: Create new video object (DAM-169)
    Given I am logged in as "archivist1@example.com"
    And I am on the home page
    And I create a new archival_video
    And I should see "Required Title"
    And I fill in "archival_video[main_title]" with "Sample Main Title"
    When I press "Save Changes"
    Then I should see "Sample Main Title"
    And I should see "Information"
    When I follow "Titles"
    Then I should see "Optional Titles"
    And I fill in "document_fields[alternative_title][]" with "Sample Alt Title"
    And I fill in "document_fields[chapter][]" with "Sample Chapter"
    And I fill in "document_fields[episode][]" with "Sample Episode"
    And I fill in "document_fields[label][]" with "Sample Label"
    And I fill in "document_fields[segment][]" with "Sample Segment"
    And I fill in "document_fields[subtitle][]" with "Sample Subtitle"
    And I fill in "document_fields[track][]" with "Sample Track"
    And I fill in "document_fields[translation][]" with "Sample Translation"
    And I fill in "document_fields[summary][]" with "Sample summary"
    And I fill in "document_fields[parts_list][]" with "Sample parts list"
    And I fill in "document_fields[note][]" with "Sample note"
    And I press "Save Changes"
    Then I should see "Required Title"
    When I follow "Subjects"
    Then I should see "Library of Congress Subject Headings"
    And I fill in "document_fields[lc_subject][]" with "Sample subject"
    And I fill in "document_fields[lc_genre][]" with "Sample genre"
    And I fill in "document_fields[event_series][]" with "Sample event series"
    And I fill in "document_fields[event_place][]" with "Sample event place"
    And I fill in "document_fields[event_date][]" with "Sample event date"
    And I press "Save Changes"
    Then I should see "Library of Congress Subject Headings"
    When I follow "Persons"
    Then I should see "Contributors"
    And I follow "Contributor"
    And I fill in "document_fields[contributor_name][0]" with "John Doe"
    And I select "artist" from "document_fields[contributor_role][0]"
    And I press "Save Changes"
    And I follow "Contributor"
    And I fill in "document_fields[contributor_name][1]" with "Jane Doe"
    And I select "host" from "document_fields[contributor_role][1]"
    And I press "Save Changes"
    And I follow "Publisher"
    And I fill in "document_fields[publisher_name][0]" with "Jane Doe"
    And I press "Save Changes"
    When I follow "Original"
    Then I should see "Original Item"
    And I fill in "document_fields[creation_date][]" with "2010-02-03"
    And I fill in "document_fields[barcode][]" with "Sample barcode"
    And the "archival_video_repository" field should contain "Rock and Roll Hall of Fame and Museum"
    And I fill in "document_fields[format][]" with "Sample format"
    And I fill in "document_fields[standard][]" with "Sample standard"
    #  These will be fixed in DAM-122
    #And the "media_type" field should contain "Moving image"
    #And the "generation" field should contain "Original"
    #And the "language" field should contain "eng"
    #And the "colors" field should contain "Color"
    And I fill in "document_fields[archival_collection][]" with "Sample achival collection"
    And I fill in "document_fields[archival_series][]" with "Sample achival series"
    And I fill in "document_fields[collection_number][]" with "Sample collection number"
    And I fill in "document_fields[accession_number][]" with "Sample accession number"
    And I fill in "document_fields[usage][]" with "Sample usage note"
    And I fill in "document_fields[condition_note][]" with "Sample condition note"
    And I fill in "document_fields[cleaning_note][]" with "Sample cleaning note"
    And I press "Save Changes"
    When I follow "Rockhall"
    Then I should see "Rockhall Fields"
    And I fill in "document_fields[notes][]" with "Sample note"
    And I press "Save Changes"
    When I follow "View"
    Then I should see the field content "main_title" contain "Sample Main Title"
    And I should see the field content "alternative_title" contain "Sample Alt Title"
    And I should see the field content "chapter" contain "Sample Chapter"
    And I should see the field content "episode" contain "Sample Episode"
    And I should see the field content "label" contain "Sample Label"
    And I should see the field content "segment" contain "Sample Segment"
    And I should see the field content "subtitle" contain "Sample Subtitle"
    And I should see the field content "track" contain "Sample Track"
    And I should see the field content "translation" contain "Sample Translation"
    And I should see the field content "summary" contain "Sample summary"
    And I should see the field content "parts_list" contain "Sample parts list"
    And I should see the field content "subjects" contain "Sample subject"
    And I should see the field content "genres" contain "Sample genre"
    And I should see the field content "event_series" contain "Sample event series"
    And I should see the field content "event_place" contain "Sample event place"
    And I should see the field content "event_date" contain "Sample event date"
    And I should see the field content "note" contain "Sample note"
    And I should see the field content "contributor" contain "John Doe"
    And I should see the field content "publisher" contain "Jane Doe"
    And I should see the field content "creation_date" contain "2010-02-03"
    And I should see the field content "barcode" contain "Sample barcode"
    And I should see the field content "repository" contain "Rock and Roll Hall of Fame and Museum"
    And I should see the field content "format" contain "Sample format"
    And I should see the field content "standard" contain "Sample standard"
    And I should see the field content "media_type" contain "Moving image"
    And I should see the field content "generation" contain "Original"
    And I should see the field content "language" contain "eng"
    And I should see the field content "colors" contain "Color"
    And I should see the field content "archival_collection" contain "Sample achival collection"
    And I should see the field content "archival_series" contain "Sample achival series"
    And I should see the field content "collection_number" contain "Sample collection number"
    And I should see the field content "accession_number" contain "Sample accession number"
    And I should see the field content "usage" contain "Sample usage note"
    And I should see the field content "condition_note" contain "Sample condition note"
    And I should see the field content "cleaning_note" contain "Sample cleaning note"
    And I should see the field content "notes" contain "Sample note"
    And I should see the field content "depositor" contain "archivist1@example.com"
    And I should see the field content "complete" contain "no"
    And I should see the field content "priority" contain "normal"