Feature:
  In order to prepare existing analog or digital video content for ingestion
  As a archivist or reviewer
  I need to created a new record for the video

  Scenario: Create new archival video object (DAM-169)
    Given I am logged in as "archivist1@example.com"
    And I am on the home page
    And I create a new archival video
    And I should see "Required Title"
    And I fill in "archival_video[main_title]" with "Sample Main Title"
    When I press "Save Changes"
    Then I should see "Sample Main Title"
    When I follow "Titles"
    Then I should see "Optional Titles"
    And I fill in "document_fields[alternative_title][]" with "Sample Alt Title"
    And I fill in "document_fields[chapter][]" with "Sample Chapter"
    And I fill in "document_fields[episode][]" with "Sample Episode"
    And I fill in "document_fields[title_label][]" with "Sample Label"
    And I fill in "document_fields[segment][]" with "Sample Segment"
    And I fill in "document_fields[subtitle][]" with "Sample Subtitle"
    And I fill in "document_fields[track][]" with "Sample Track"
    And I fill in "document_fields[translation][]" with "Sample Translation"
    And I fill in "document_fields[summary][]" with "Sample summary"
    And I fill in "document_fields[parts_list][]" with "Sample parts list"
    And I fill in "document_fields[note][]" with "Sample note"
    And I press "Save Changes"
    Then I should see "Required Title"
    When I follow "Subjects"
    Then I should see "Library of Congress Subject Headings"
    And I fill in "document_fields[lc_subject][]" with "Sample subject"
    And I fill in "document_fields[lc_genre][]" with "Sample genre"
    And I fill in "document_fields[event_series][]" with "Sample event series"
    And I fill in "document_fields[event_place][]" with "Sample event place"
    And I fill in "document_fields[event_date][]" with "2010-02-03"
    And I press "Save Changes"
    Then I should see "Library of Congress Subject Headings"
    When I follow "Persons"
    Then I should see "Contributors"
    And I follow "Contributor"
    And I fill in "document_fields[contributor_name][0]" with "John Doe"
    And I select "artist" from "document_fields[contributor_role][0]"
    And I press "Save Changes"
    And I follow "Contributor"
    And I fill in "document_fields[contributor_name][1]" with "Jane Doe"
    And I select "host" from "document_fields[contributor_role][1]"
    And I press "Save Changes"
    And I follow "Publisher"
    And I fill in "document_fields[publisher_name][0]" with "Jane Doe"
    And I press "Save Changes"
    When I follow "Original"
    Then I should see "Original Item"
    And I fill in "document_fields[creation_date][]" with "2010-02-03"
    And I fill in "document_fields[barcode][]" with "Sample barcode"
    And the "archival_video_repository" field should contain "Rock and Roll Hall of Fame and Museum"
    And I fill in "document_fields[format][]" with "Sample format"
    And the following should be selected within "fieldset#original_fields"
      | archival_video_colors | Color |
    And I select the following within "fieldset#original_fields"
      | archival_video_standard | NTSC |
    And I fill in "document_fields[generation][]" with "Original"
    And I fill in "document_fields[language][]" with "eng"
    And I fill in "document_fields[archival_collection][]" with "Sample achival collection"
    And I fill in "document_fields[archival_series][]" with "Sample achival series"
    And I fill in "document_fields[collection_number][]" with "Sample collection number"
    And I fill in "document_fields[accession_number][]" with "Sample accession number"
    And I fill in "document_fields[usage][]" with "Sample usage note"
    And I fill in "document_fields[condition_note][]" with "Sample condition note"
    And I fill in "document_fields[cleaning_note][]" with "Sample cleaning note"
    And I press "Save Changes"
    When I follow "Rockhall"
    Then I should see "Rockhall Fields"
    And I fill in "document_fields[notes][]" with "Sample note"
    And I press "Save Changes"
    When I follow "View"
    Then I should see the field content "main_title_t" contain "Sample Main Title"
    And I should see the field content "alternative_title_t" contain "Sample Alt Title"
    And I should see the field content "chapter_t" contain "Sample Chapter"
    And I should see the field content "episode_t" contain "Sample Episode"
    And I should see the field content "label_t" contain "Sample Label"
    And I should see the field content "segment_t" contain "Sample Segment"
    And I should see the field content "subtitle_t" contain "Sample Subtitle"
    And I should see the field content "track_t" contain "Sample Track"
    And I should see the field content "translation_t" contain "Sample Translation"
    And I should see the field content "summary_t" contain "Sample summary"
    And I should see the field content "parts_list_t" contain "Sample parts list"
    And I should see the field content "subjects_t" contain "Sample subject"
    And I should see the field content "genres_t" contain "Sample genre"
    And I should see the field content "event_series_t" contain "Sample event series"
    And I should see the field content "event_place_t" contain "Sample event place"
    And I should see the field content "event_date_t" contain "2010-02-03"
    And I should see the field content "note_t" contain "Sample note"
    And I should see the field content "contributors_display" contain "John Doe"
    And I should see the field content "publisher_display" contain "Jane Doe"
    And I should see the field content "creation_date_t" contain "2010-02-03"
    And I should see the field content "barcode_t" contain "Sample barcode"
    And I should see the field content "repository_t" contain "Rock and Roll Hall of Fame and Museum"
    And I should see the field content "format_t" contain "Sample format"
    And I should see the field content "standard_t" contain "NTSC"
    And I should see the field content "media_type_t" contain "Moving image"
    And I should see the field content "generation_t" contain "Original"
    And I should see the field content "language_t" contain "eng"
    And I should see the field content "colors_t" contain "Color"
    And I should see the field content "archival_collection_t" contain "Sample achival collection"
    And I should see the field content "archival_series_t" contain "Sample achival series"
    And I should see the field content "collection_number_t" contain "Sample collection number"
    And I should see the field content "accession_number_t" contain "Sample accession number"
    And I should see the field content "usage_t" contain "Sample usage note"
    And I should see the field content "condition_note_t" contain "Sample condition note"
    And I should see the field content "cleaning_note_t" contain "Sample cleaning note"
    And I should see the field content "depositor_t" contain "archivist1@example.com"

  Scenario: Create new digital video object without a title (DAM-210)
    Given I am logged in as "archivist1@example.com"
    And I am on the home page
    And I create a new archival video
    When I press "Save Changes"
    Then I should see "Main title can't be blank"

  Scenario: Validate correct date format for all date fields (DAM-211)
    Given I am logged in as "archivist1@example.com"
    And I am on the edit digital video page for rockhall:fixture_pbcore_document1
    When I follow "Subjects"
    And I fill in "document_fields[event_date][]" with "bogus date"
    And I press "Save Changes"
    Then I should see "Date must be in YYYY-MM-DD format"
    When I follow "Original"
    And I fill in "document_fields[creation_date][]" with "bogus"
    And I press "Save Changes"
    Then I should see "Date must be in YYYY-MM-DD format"

  Scenario: Partial dates in solr (DAM-212)
    Given I am logged in as "archivist1@example.com"
    And I am on the home page
    And I create a new archival video
    And I should see "Required Title"
    And I fill in "archival_video[main_title]" with "Sample Main Title"
    When I press "Save Changes"
    Then I should see "Sample Main Title"
    When I follow "Subjects"
    And I fill in "document_fields[event_date][]" with "1999"
    And I press "Save Changes"
    Then the "event_date_0" field should contain "1999"
    And I fill in "document_fields[event_date][]" with "2003-12"
    And I press "Save Changes"
    Then the "event_date_0" field should contain "2003-12"
    When I follow "Original"
    And I fill in "document_fields[creation_date][]" with "1999"
    And I press "Save Changes"
    Then the "archival_video_creation_date" field should contain "1999"
    And I fill in "document_fields[creation_date][]" with "2003-12"
    And I press "Save Changes"
    Then the "archival_video_creation_date" field should contain "2003-12"









