Feature:
  In order to prepare existing analog or digital video content for ingestion
  As a archivist or reviewer
  I need to created a new record for the video

  Scenario: Create new video object (DAM-169)
    Given I am logged in as "archivist1@example.com"
    And I am on the home page
    And I create a new archival_video
    Then I should see "Content"
    And I should see "Required Title"
    And I fill in "asset[descMetadata][main_title][0]" with "Sample Main Title"
    And I fill in "asset[descMetadata][alternative_title][0]" with "Sample Alt Title"
    And I fill in "asset[descMetadata][chapter][0]" with "Sample Chapter"
    And I fill in "asset[descMetadata][episode][0]" with "Sample Episode"
    And I fill in "asset[descMetadata][label][0]" with "Sample Label"
    And I fill in "asset[descMetadata][segment][0]" with "Sample Segment"
    And I fill in "asset[descMetadata][subtitle][0]" with "Sample Subtitle"
    And I fill in "asset[descMetadata][track][0]" with "Sample Track"
    And I fill in "asset[descMetadata][translation][0]" with "Sample Translation"
    And I fill in "asset[descMetadata][summary][0]" with "Sample summary"
    And I fill in "asset[descMetadata][parts_list][0]" with "Sample parts list"
    And I fill in "asset[descMetadata][note][0]" with "Sample note"
    And I press "Submit"
    And I fill in "asset[descMetadata][alternative_title][1]" with "Second Sample Alt Title"
    And I fill in "asset[descMetadata][chapter][1]" with "Second Sample Chapter"
    And I fill in "asset[descMetadata][episode][1]" with "Second Sample Episode"
    And I fill in "asset[descMetadata][label][1]" with "Second Sample Label"
    And I fill in "asset[descMetadata][segment][1]" with "Second Sample Segment"
    And I fill in "asset[descMetadata][subtitle][1]" with "Second Sample Subtitle"
    And I fill in "asset[descMetadata][track][1]" with "Second Sample Track"
    And I fill in "asset[descMetadata][translation][1]" with "Second Sample Translation"
    And I fill in "asset[descMetadata][note][1]" with "Second Sample note"
    When I choose "wf_step_titles"
    And I press "Submit"
    Then I should see "Subject Fields"
    And I fill in "asset[descMetadata][lc_subject][0]" with "Sample subject"
    And I fill in "asset[descMetadata][lc_genre][0]" with "Sample genre"
    And I fill in "asset[descMetadata][event_series][0]" with "Sample event series"
    And I fill in "asset[descMetadata][event_place][0]" with "Sample event place"
    And I fill in "asset[descMetadata][event_date][0]" with "Sample event date"
    And I press "Submit"
    And I fill in "asset[descMetadata][lc_subject][1]" with "Second Sample subject"
    And I fill in "asset[descMetadata][lc_genre][1]" with "Second Sample genre"
    When I choose "wf_step_subjects"
    And I press "Submit"
    Then I should see "Contributors"
    And I press "Add contributor"
    Then I should see "Contributor"
    And I fill in "asset[descMetadata][contributor_0_name][0]" with "John Doe"
    And I press "Submit"
    Then the "contributor_0_name" field within "#contributor" should contain "John Doe"
    And I press "Add publisher"
    Then I should see "Publisher"
    And I fill in "asset[descMetadata][publisher_0_name][0]" with "Jane Doe"
    And I press "Submit"
    Then the "publisher_0_name" field within "#publisher" should contain "Jane Doe"
    When I choose "wf_step_persons"
    And I press "Submit"
    Then I should see "Original Item"
    And I fill in "asset[descMetadata][creation_date][0]" with "2010-02-03"
    And I fill in "asset[descMetadata][barcode][0]" with "Sample barcode"
    And the "repository" field should contain "Rock and Roll Hall of Fame and Museum"
    And I fill in "asset[descMetadata][format][0]" with "Sample format"
    And I fill in "asset[descMetadata][standard][0]" with "Sample standard"
    And the "media_type" field should contain "Moving image"
    And the "generation" field should contain "Original"
    And the "language" field should contain "eng"
    And the "colors" field should contain "Color"
    And I fill in "asset[descMetadata][archival_collection][0]" with "Sample achival collection"
    And I fill in "asset[descMetadata][archival_series][0]" with "Sample achival series"
    And I fill in "asset[descMetadata][collection_number][0]" with "Sample collection number"
    And I fill in "asset[descMetadata][accession_number][0]" with "Sample accession number"
    And I fill in "asset[descMetadata][usage][0]" with "Sample usage note"
    And I fill in "asset[descMetadata][condition_note][0]" with "Sample condition note"
    And I fill in "asset[descMetadata][cleaning_note][0]" with "Sample cleaning note"
    And I press "Submit"
    Then I should see "Rockhall Fields"
    And I fill in "asset[properties][notes][0]" with "Sample note"
    And I fill in "asset[properties][submission][0]" with "Sample file submission"
    And I fill in "asset[properties][access][0]" with "Sample access"
    And I press "Save and Finish"
    Then I should see the field content "main_title" contain "Sample Main Title"
    And I should see the field content "alternative_title" contain "Sample Alt Title"
    And I should see the field content "alternative_title" contain "Second Sample Alt Title"
    And I should see the field content "chapter" contain "Sample Chapter"
    And I should see the field content "chapter" contain "Second Sample Chapter"
    And I should see the field content "episode" contain "Sample Episode"
    And I should see the field content "episode" contain "Second Sample Episode"
    And I should see the field content "label" contain "Sample Label"
    And I should see the field content "label" contain "Second Sample Label"
    And I should see the field content "segment" contain "Sample Segment"
    And I should see the field content "segment" contain "Second Sample Segment"
    And I should see the field content "subtitle" contain "Sample Subtitle"
    And I should see the field content "subtitle" contain "Second Sample Subtitle"
    And I should see the field content "track" contain "Sample Track"
    And I should see the field content "track" contain "Second Sample Track"
    And I should see the field content "translation" contain "Sample Translation"
    And I should see the field content "translation" contain "Second Sample Translation"
    And I should see the field content "summary" contain "Sample summary"
    And I should see the field content "parts_list" contain "Sample parts list"
    And I should see the field content "subjects" contain "Sample subject"
    And I should see the field content "subjects" contain "Second Sample subject"
    And I should see the field content "genres" contain "Sample genre"
    And I should see the field content "genres" contain "Second Sample genre"
    And I should see the field content "event_series" contain "Sample event series"
    And I should see the field content "event_place" contain "Sample event place"
    And I should see the field content "event_date" contain "Sample event date"
    And I should see the field content "note" contain "Sample note"
    And I should see the field content "note" contain "Second Sample note"
    And I should see the field content "contributor" contain "John Doe"
    And I should see the field content "publisher" contain "Jane Doe"
    And I should see the field content "creation_date" contain "2010-02-03"
    And I should see the field content "barcode" contain "Sample barcode"
    And I should see the field content "repository" contain "Rock and Roll Hall of Fame and Museum"
    And I should see the field content "format" contain "Sample format"
    And I should see the field content "standard" contain "Sample standard"
    And I should see the field content "media_type" contain "Moving image"
    And I should see the field content "generation" contain "Original"
    And I should see the field content "language" contain "eng"
    And I should see the field content "colors" contain "Color"
    And I should see the field content "archival_collection" contain "Sample achival collection"
    And I should see the field content "archival_series" contain "Sample achival series"
    And I should see the field content "collection_number" contain "Sample collection number"
    And I should see the field content "accession_number" contain "Sample accession number"
    And I should see the field content "usage" contain "Sample usage note"
    And I should see the field content "condition_note" contain "Sample condition note"
    And I should see the field content "cleaning_note" contain "Sample cleaning note"
    And I should see the field content "notes" contain "Sample note"
    And I should see the field content "depositor" contain "archivist1@example.com"
    And I should see the field content "submission" contain "Sample file submission"
    And I should see the field content "access" contain "Sample access"
    And I should see the field content "complete" contain "no"
    And I should see the field content "priority" contain "normal"