Feature:
  In order to prepare born-digital video content for ingestion
  As an archivist
  I need to created a new record for the video

  Scenario: Create new digital video object (DAM-169)
    Given I am logged in as "archivist1@example.com"
    And I am on the home page
    And I create a new digital_video
    Then I should see "New Digital Video"
    And I should see "Required Title"
    And I fill in "digital_video[main_title]" with "Sample Main Title"
    When I press "Save Changes"
    And I should see "Sample Main Title"
    When I follow "Titles"
    Then I should see "Optional Titles"
    And I fill in "document_fields[alternative_title][]" with "Sample Alt Title"
    And I press "+" within "div#additional_alternative_title_clone"
    And I fill in "document_fields[chapter][]" with "Sample Chapter"
    And I fill in "document_fields[episode][]" with "Sample Episode"
    And I fill in "document_fields[title_label][]" with "Sample Label"
    And I fill in "document_fields[segment][]" with "Sample Segment"
    And I fill in "document_fields[subtitle][]" with "Sample Subtitle"
    And I fill in "document_fields[track][]" with "Sample Track"
    And I fill in "document_fields[translation][]" with "Sample Translation"
    And I fill in "document_fields[summary][]" with "Sample summary"
    And I fill in "document_fields[parts_list][]" with "Sample parts list"
    And I fill in "document_fields[note][]" with "Sample note"
    And I press "Save Changes"
    Then I should see "Required Title"
    When I follow "Subjects"
    Then I should see "Library of Congress Subject Headings"
    And I fill in "document_fields[lc_subject][]" with "Sample subject"
    And I fill in "document_fields[lc_genre][]" with "Sample genre"
    And I fill in "document_fields[event_series][]" with "Sample event series"
    And I fill in "document_fields[event_place][]" with "Sample event place"
    And I fill in "document_fields[event_date][]" with "Sample event date"
    And I press "Save Changes"
    Then I should see "Library of Congress Subject Headings"
    When I follow "Persons"
    Then I should see "Contributors"
    And I follow "Contributor"
    And I fill in "document_fields[contributor_name][0]" with "John Doe"
    And I select "artist" from "document_fields[contributor_role][0]"
    And I press "Save Changes"
    And I follow "Contributor"
    And I fill in "document_fields[contributor_name][1]" with "Jane Doe"
    And I select "host" from "document_fields[contributor_role][1]"
    And I press "Save Changes"
    And I follow "Publisher"
    And I fill in "document_fields[publisher_name][0]" with "Jane Doe"
    And I press "Save Changes"
    When I follow "Collection"
    Then I should see "Archival Information"
    And I fill in "document_fields[archival_collection][]" with "Sample achival collection"
    And I fill in "document_fields[archival_series][]" with "Sample achival series"
    And I fill in "document_fields[collection_number][]" with "Sample collection number"
    And I fill in "document_fields[accession_number][]" with "Sample accession number"
    And I fill in "document_fields[usage][]" with "Sample usage note"
    And I press "Save Changes"
    When I follow "Rockhall"
    Then I should see "Rockhall Fields"
    And I fill in "document_fields[notes][]" with "Sample note"
    And I press "Save Changes"
    When I follow "View"
    Then I should see the field content "main_title_t" contain "Sample Main Title"
    And I should see the field content "alternative_title_t" contain "Sample Alt Title"
    And I should see the field content "chapter_t" contain "Sample Chapter"
    And I should see the field content "episode_t" contain "Sample Episode"
    And I should see the field content "label_t" contain "Sample Label"
    And I should see the field content "segment_t" contain "Sample Segment"
    And I should see the field content "subtitle_t" contain "Sample Subtitle"
    And I should see the field content "track_t" contain "Sample Track"
    And I should see the field content "translation_t" contain "Sample Translation"
    And I should see the field content "summary_t" contain "Sample summary"
    And I should see the field content "parts_list_t" contain "Sample parts list"
    And I should see the field content "subjects_t" contain "Sample subject"
    And I should see the field content "genres_t" contain "Sample genre"
    And I should see the field content "event_series_t" contain "Sample event series"
    And I should see the field content "event_place_t" contain "Sample event place"
    And I should see the field content "event_date_t" contain "Sample event date"
    And I should see the field content "note_t" contain "Sample note"
    And I should see the field content "contributors_display" contain "John Doe"
    And I should see the field content "publisher_display" contain "Jane Doe"
    And I should see the field content "archival_collection_t" contain "Sample achival collection"
    And I should see the field content "archival_series_t" contain "Sample achival series"
    And I should see the field content "collection_number_t" contain "Sample collection number"
    And I should see the field content "accession_number_t" contain "Sample accession number"
    And I should see the field content "usage_t" contain "Sample usage note"
    And I should see the field content "depositor_t" contain "archivist1@example.com"

  Scenario: Create new digital video object without a title (DAM-210)
    Given I am logged in as "archivist1@example.com"
    And I am on the home page
    And I create a new digital_video
    When I press "Save Changes"
    Then I should see "Main title can't be blank"