development:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://localhost:8984/solr/hydra-dev
test: &TEST
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://localhost:8984/solr/hydra-test
production:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://localhost:8984/solr/hydra-dev
cucumber:
  <<: *TEST
