# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora.
development:
  url: http://localhost:8985/solr/hydra-dev
test: &TEST
  url: http://localhost:8985/solr/hydra-test
cucumber:
  <<: *TEST
production:
    url: http://localhost:8985/solr/hydra-dev
