#!/bin/bash
# Tests rake task for converting old models to new
echo "Epmtying Fedora..."
bin/rake rockhall:fedora:empty
echo "Loading conversion fixtures from spec/fixtures/convert"
bin/rake rockhall:fedora:load DIR=spec/fixtures/convert
echo "Converting videos..."
bin/rake rockhall:convert:videos
echo "Converting again to check"
bin/rake rockhall:convert:videos