#!/bin/bash
#echo -n "Reloading ActiveRecord fixtures: "
#bundle exec rake db:fixtures:load
#echo "done."
echo -n "Re-indexing solr: "
bundle exec rake rockhall:solr:index_all
echo -n "Emptying fedora: "
bundle exec rake rockhall:fedora:empty
echo "done."
echo -n "Cleaning out solr dev: "
bundle exec rake rockhall:solr:clean
echo "done."
echo -n "Loading fixtures: "
bundle exec rake rockhall:fedora:load
echo "done."
echo -n "Re-indexing solr: "
bundle exec rake rockhall:solr:index_all
echo -n "Cleaning out solr test: "
RAILS_ENV=test bundle exec rake rockhall:solr:clean
echo "done."
echo -n "Indexing solr test: "
RAILS_ENV=test bundle exec rake rockhall:solr:index_all
# no echo here since rake task outputs results and a newline