#!/bin/bash
echo -n "Reloading ActiveRecord fixtures:"
bin/rake db:fixtures:load FIXTURES_PATH=spec/fixtures/ar
echo "done."
echo -n "Re-indexing solr: "
bin/rake rockhall:solr:index_all
echo -n "Removing unwanted objects from fedora: "
bin/rake rockhall:fedora:clean
echo "done."
echo -n "Cleaning out solr dev: "
bin/rake rockhall:solr:clean
echo "done."
echo -n "Indexing solr dev: "
bin/rake rockhall:solr:index_all
# no echo here since rake task outputs results and a newline
echo -n "Cleaning out solr test: "
RAILS_ENV=test bin/rake rockhall:solr:clean
echo "done."
echo -n "Indexing solr test: "
RAILS_ENV=test bin/rake rockhall:solr:index_all
# no echo here since rake task outputs results and a newline